# Site settings
title: Bolot Kalil — Full-Stack Developer & Hardware Innovator
description: Engineer, full-stack developer, and co-founder of Exon AI. I build powerful mobile apps, scalable backend systems, and high-tech hardware — from AI-powered robots to sustainable energy devices. Explore my portfolio of innovations, projects, and engineering work.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Bolot Kalil
user_title: Engineer, Full-Stack Developer & Co-Founder of Exon AI
user_description: >
  I build mobile apps, scalable backend systems, and high-tech hardware — from AI-powered robots to sustainable energy devices. Co-founder of Exon AI and creator of innovative engineering projects across mobile, AI, and embedded systems.

email: bolotkalil@gmail.com
twitter_username: bolotkalil
github_username: bolotkalil
gplus_username: bolotkalil  # (optional — deprecated for public use)

# Google Analytics
google-analytics:
  id: ""  # Add your tracking ID here if needed

exclude:
  - package.json
  - src
  - node_modules